version: "3.8"
services:
    php:
        image: ghcr.io/vincfleurette/oddoslim-api:latest
        restart: always
        volumes:
            - ./public:/var/www/html/public:ro
            - ./.env:/var/www/html/.env:ro
            - ./storage:/var/www/html/storage
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        networks:
            - webnet

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html/public:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8000:80"
        networks:
            - webnet

networks:
    webnet:
        driver: bridge
