# Fix 5: docker-compose.yml (UPDATED avec Redis)
version: "3.8"
services:
    php:
        image: ghcr.io/vincfleurette/oddoslim-api:latest
        restart: always
        volumes:
            - ./public:/var/www/html/public:ro
            - ./.env:/var/www/html/.env:ro
            # Utiliser un volume temporaire pour le cache
            - cache_volume:/tmp/oddo_cache
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
            - PHP_DISPLAY_ERRORS=0
            - PHP_LOG_ERRORS=1
        networks:
            - webnet
        depends_on:
            - redis

    # Ajouter Redis pour un cache plus robuste
    redis:
        image: redis:7-alpine
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        networks:
            - webnet

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html/public:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8000:80"
        networks:
            - webnet

networks:
    webnet:
        driver: bridge

volumes:
    cache_volume:
        driver: local
    redis_data:
        driver: local
