version: "3.8"
services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        # plus de volume ./:/var/www/html
        volumes:
            - ./storage:/var/www/html/storage # si vous avez besoin de persister storage
        networks:
            - webnet

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html/public:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8000:80"
        networks:
            - webnet

networks:
    webnet:
        driver: bridge
