name: CI · Build & Publish Docker Image

on:
    push:
        branches: [Master]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # 1) Setup Buildx with the container driver
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  driver-opts: network=host

            # 2) Login to GHCR
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.CR_PAT }}

            # 3) Build & push with cache
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./php/Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/oddoslim-api:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
